// src/mockCredits.js
export const MOCK_CREDITS = [
    {
      id: "rec_001",
      Date: "2025-11-01",
      Type: "Item Credit",
      "Credit Type": "Price Discrepancy",
      "Customer Number": "100234",
      "Invoice Number": "987654",
      "Item Number": "NONMB600",
      QTY: 2,
      "Unit Price": 10.5,
      "Extended Price": 21.0,
      "Corrected Unit Price": 9.0,
      "Credit Request Total": 3.0,
      "Reason for Credit": "Contract price not applied",
      "Requested By": "Sales Rep A",
      "Sales Rep": "Rep A",
      Status: "Approved",
      "Ticket Number": "ITOP-12345",
    },
    {
      id: "rec_002",
      Date: "2025-11-03",
      Type: "Item Credit",
      "Credit Type": "Short Shipment",
      "Customer Number": "100567",
      "Invoice Number": "123456",
      "Item Number": "MDSM3ACUFFA",
      QTY: 10,
      "Unit Price": 5.0,
      "Extended Price": 50.0,
      "Corrected Unit Price": 0.0,
      "Credit Request Total": 50.0,
      "Reason for Credit": "Items never received",
      "Requested By": "Sales Rep B",
      "Sales Rep": "Rep B",
      Status: "Pending",
      "Ticket Number": "ITOP-67890",
    },
    {
      id: "rec_003",
      Date: "2025-11-05",
      Type: "Invoice Credit",
      "Credit Type": "Tax Error",
      "Customer Number": "100234",
      "Invoice Number": "555777",
      "Item Number": "NONORG001",
      QTY: 1,
      "Unit Price": 100.0,
      "Extended Price": 100.0,
      "Corrected Unit Price": 95.0,
      "Credit Request Total": 5.0,
      "Reason for Credit": "Tax exempt facility",
      "Requested By": "Billing",
      "Sales Rep": "Rep A",
      Status: "Denied",
      "Ticket Number": "ITOP-99999",
    },
  ];